### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by sumon0002001**
- Here I built a social media app called “Stay in touch”.
- Created using the RoRSocialScaffold by Microverse.
-  implemented a Friendship system where you can add/invite to be friends as well as a decline feature.

### CODE REVIEW

**Comment by sumon0002001** [comment]
-I have filled up all the requirements for milestone 2 and 3 in the previous milestone.

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @ & @**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] when a friendship request is pending you should display the pending status in the users index page next to the person and in that person's user page.
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by sumon0002001** [comment]
-first requirement i have already done in the second milestone. when I log in I can see the person with the pending status with 2 options either accept or delete
-  This requirement is also done the second milestone. After accepting request another row is created.

**Comment by mahmoud717** [comment]
- the first requirement is for the person who is sending the request.
- please tell me what line is the second requirement is implemented in and in which file.

**Comment by sumon0002001** [comment]
-for second requirement- in the views folder-user folder-index.html.erb- it shows all the users who are friends.

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

#### Note: I will use examples to try and explain the changes required
1). **If, for example, Jen was to send Mercy a friend request, she should be able to do it from the users' list page or Mercy's profile page. You have only implemented the action in the users' list page.**

2). **So I have two users, Jen and Mercy. When Jen clicks the add friend button next to Mercy's name, then after the button is removed there should be a sentence reading pending status or something, next to Mercy's name. See an example in the screenshot below.**

 before a request is sent  | After a request is sent
 ---------------------------| ------------------------
before_request | after_request

3). **Let's say Mercy accepts Jen's friend request. When that happens, your Friendship table array should show two friendships created instead of one. So in your case below, 
friend_table
you should ensure that there is another Friendship created with` user_id: 2` and `friend_id:1`, (this is what is called reversed user-friend pair). Note: It is created automatically only after a friendship confirmed status is true.**

4). **Remember to add RSpec tests for any methods you implement for the above changes**

### Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by NtwaliHeritier — APPROVED** [review]
### STATUS: APPROVED✔
Hello team,
Thank you for making the required changes.
You can merge the branches.

**Pull request merged**
